/*
 *		Lanuage Code Mapper
 *
 *
 *		This file contains a JavaScript object that maps ISO 639-1 language codes to their corresponding language names. It has a comment that instructs Istanbul code
 *		coverage tool to ignore this file during testing. The object contains 184 key-value pairs, with each key being a two-letter language code and each value being the
 *		name of the language.
 */
/* istanbul ignore file */

const langsByCode = {
  aa: 'Afar',
  ab: 'Abkhazian',
  ae: 'Avestan',
  af: 'Afrikaans',
  ak: 'Akan',
  am: 'Amharic',
  an: 'Aragonese',
  ar: 'Arabic',
  as: 'Assamese',
  av: 'Avaric',
  ay: 'Aymara',
  az: 'Azerbaijani',
  ba: 'Bashkir',
  be: 'Belarusian',
  bg: 'Bulgarian',
  bh: 'Bihari languages',
  bi: 'Bislama',
  bm: 'Bambara',
  bn: 'Bengali',
  bo: 'Tibetan',
  br: 'Breton',
  bs: 'Bosnian',
  ca: 'Catalan',
  ce: 'Chechen',
  ch: 'Chamorro',
  co: 'Corsican',
  cr: 'Cree',
  cs: 'Czech',
  cv: 'Chuvash',
  cy: 'Welsh',
  da: 'Danish',
  de: 'German',
  dv: 'Divehi',
  dz: 'Dzongkha',
  ee: 'Ewe',
  el: 'Greek',
  en: 'English',
  eo: 'Esperanto',
  es: 'Spanish',
  et: 'Estonian',
  eu: 'Basque',
  fa: 'Persian',
  ff: 'Fulah',
  fi: 'Finnish',
  fj: 'Fijian',
  fo: 'Faroese',
  fr: 'French',
  fy: 'Western Frisian',
  ga: 'Irish',
  gd: 'Gaelic',
  gl: 'Galician',
  gn: 'Guarani',
  gu: 'Gujarati',
  gv: 'Manx',
  ha: 'Hausa',
  he: 'Hebrew',
  hi: 'Hindi',
  ho: 'Hiri Motu',
  hr: 'Croatian',
  ht: 'Haitian Creole',
  hu: 'Hungarian',
  hy: 'Armenian',
  hz: 'Herero',
  id: 'Indonesian',
  ie: 'Interlingue',
  ig: 'Igbo',
  ii: 'Sichuan Yi',
  ik: 'Inupiaq',
  io: 'Ido',
  is: 'Icelandic',
  it: 'Italian',
  iu: 'Inuktitut',
  ja: 'Japanese',
  jv: 'Javanese',
  ka: 'Georgian',
  kg: 'Kongo',
  ki: 'Kikuyu',
  kj: 'Kwanyama',
  kk: 'Kazakh',
  kl: 'Kalaallisut',
  km: 'Central Khmer',
  kn: 'Kannada',
  ko: 'Korean',
  kr: 'Kanuri',
  ks: 'Kashmiri',
  ku: 'Kurdish',
  kv: 'Komi',
  kw: 'Cornish',
  ky: 'Kyrgyz',
  la: 'Latin',
  lb: 'Luxembourgish',
  lg: 'Ganda',
  li: 'Limburgan',
  ln: 'Lingala',
  lo: 'Lao',
  lt: 'Lithuanian',
  lu: 'Luba-Katanga',
  lv: 'Latvian',
  mg: 'Malagasy',
  mh: 'Marshallese',
  mi: 'Maori',
  mk: 'Macedonian',
  ml: 'Malayalam',
  mn: 'Mongolian',
  mr: 'Marathi',
  ms: 'Malay',
  mt: 'Maltese',
  my: 'Burmese',
  na: 'Nauru',
  nb: 'Norwegian Bokmål',
  nd: 'North Ndebele',
  ne: 'Nepali',
  ng: 'Ndonga',
  nl: 'Dutch',
  nn: 'Norwegian Nynorsk',
  no: 'Norwegian',
  nr: 'South Ndebele',
  nv: 'Navajo',
  ny: 'Nyanja',
  oc: 'Occitan',
  oj: 'Ojibwa',
  om: 'Oromo',
  or: 'Oriya',
  os: 'Ossetian',
  pa: 'Punjabi',
  pi: 'Pali',
  pl: 'Polish',
  ps: 'Pashto',
  pt: 'Portuguese',
  qu: 'Quechua',
  rm: 'Romansh',
  rn: 'Rundi',
  ro: 'Romanian',
  ru: 'Russian',
  rw: 'Kinyarwanda',
  sa: 'Sanskrit',
  sc: 'Sardinian',
  sd: 'Sindhi',
  se: 'Northern Sami',
  sg: 'Sango',
  si: 'Sinhalese',
  sk: 'Slovak',
  sl: 'Slovenian',
  sm: 'Samoan',
  sn: 'Shona',
  so: 'Somali',
  sq: 'Albanian',
  sr: 'Serbian',
  ss: 'Swati',
  st: 'Sotho, Southern',
  su: 'Sundanese',
  sv: 'Swedish',
  sw: 'Swahili',
  ta: 'Tamil',
  te: 'Telugu',
  tg: 'Tajik',
  th: 'Thai',
  ti: 'Tigrinya',
  tk: 'Turkmen',
  tl: 'Tagalog',
  tn: 'Tswana',
  to: 'Tonga (Tonga Islands)',
  tr: 'Turkish',
  ts: 'Tsonga',
  tt: 'Tatar',
  tw: 'Twi',
  ty: 'Tahitian',
  ug: 'Uyghur',
  uk: 'Ukrainian',
  ur: 'Urdu',
  uz: 'Uzbek',
  ve: 'Venda',
  vi: 'Vietnamese',
  vo: 'Volapük',
  wa: 'Walloon',
  wo: 'Wolof',
  xh: 'Xhosa',
  yi: 'Yiddish',
  yo: 'Yoruba',
  za: 'Zhuang',
  zh: 'Chinese',
  zu: 'Zulu',
};

const langsByName = {
  Afar: 'aa',
  Abkhazian: 'ab',
  Avestan: 'ae',
  Afrikaans: 'af',
  Akan: 'ak',
  Amharic: 'am',
  Aragonese: 'an',
  Arabic: 'ar',
  Assamese: 'as',
  Avaric: 'av',
  Aymara: 'ay',
  Azerbaijani: 'az',
  Bashkir: 'ba',
  Belarusian: 'be',
  Bulgarian: 'bg',
  'Bihari languages': 'bh',
  Bislama: 'bi',
  Bambara: 'bm',
  Bengali: 'bn',
  Tibetan: 'bo',
  Breton: 'br',
  Bosnian: 'bs',
  Catalan: 'ca',
  Chechen: 'ce',
  Chamorro: 'ch',
  Corsican: 'co',
  Cree: 'cr',
  Czech: 'cs',
  Chuvash: 'cv',
  Welsh: 'cy',
  Danish: 'da',
  German: 'de',
  Divehi: 'dv',
  Dzongkha: 'dz',
  Ewe: 'ee',
  Greek: 'el',
  English: 'en',
  Esperanto: 'eo',
  Spanish: 'es',
  Estonian: 'et',
  Basque: 'eu',
  Persian: 'fa',
  Fulah: 'ff',
  Finnish: 'fi',
  Fijian: 'fj',
  Faroese: 'fo',
  French: 'fr',
  'Western Frisian': 'fy',
  Irish: 'ga',
  Gaelic: 'gd',
  Galician: 'gl',
  Guarani: 'gn',
  Gujarati: 'gu',
  Manx: 'gv',
  Hausa: 'ha',
  Hebrew: 'he',
  Hindi: 'hi',
  'Hiri Motu': 'ho',
  Croatian: 'hr',
  'Haitian Creole': 'ht',
  Hungarian: 'hu',
  Armenian: 'hy',
  Herero: 'hz',
  Indonesian: 'id',
  Interlingue: 'ie',
  Igbo: 'ig',
  'Sichuan Yi': 'ii',
  Inupiaq: 'ik',
  Ido: 'io',
  Icelandic: 'is',
  Italian: 'it',
  Inuktitut: 'iu',
  Japanese: 'ja',
  Javanese: 'jv',
  Georgian: 'ka',
  Kongo: 'kg',
  Kikuyu: 'ki',
  Kwanyama: 'kj',
  Kazakh: 'kk',
  Kalaallisut: 'kl',
  'Central Khmer': 'km',
  Kannada: 'kn',
  Korean: 'ko',
  Kanuri: 'kr',
  Kashmiri: 'ks',
  Kurdish: 'ku',
  Komi: 'kv',
  Cornish: 'kw',
  Kyrgyz: 'ky',
  Latin: 'la',
  Luxembourgish: 'lb',
  Ganda: 'lg',
  Limburgan: 'li',
  Lingala: 'ln',
  Lao: 'lo',
  Lithuanian: 'lt',
  'Luba-Katanga': 'lu',
  Latvian: 'lv',
  Malagasy: 'mg',
  Marshallese: 'mh',
  Maori: 'mi',
  Macedonian: 'mk',
  Malayalam: 'ml',
  Mongolian: 'mn',
  Marathi: 'mr',
  Malay: 'ms',
  Maltese: 'mt',
  Burmese: 'my',
  Nauru: 'na',
  'Norwegian Bokmål': 'nb',
  'North Ndebele': 'nd',
  Nepali: 'ne',
  Ndonga: 'ng',
  Dutch: 'nl',
  'Norwegian Nynorsk': 'nn',
  Norwegian: 'no',
  'South Ndebele': 'nr',
  Navajo: 'nv',
  Nyanja: 'ny',
  Occitan: 'oc',
  Ojibwa: 'oj',
  Oromo: 'om',
  Oriya: 'or',
  Ossetian: 'os',
  Punjabi: 'pa',
  Pali: 'pi',
  Polish: 'pl',
  Pashto: 'ps',
  Portuguese: 'pt',
  Quechua: 'qu',
  Romansh: 'rm',
  Rundi: 'rn',
  Romanian: 'ro',
  Russian: 'ru',
  Kinyarwanda: 'rw',
  Sanskrit: 'sa',
  Sardinian: 'sc',
  Sindhi: 'sd',
  'Northern Sami': 'se',
  Sango: 'sg',
  Sinhalese: 'si',
  Slovak: 'sk',
  Slovenian: 'sl',
  Samoan: 'sm',
  Shona: 'sn',
  Somali: 'so',
  Albanian: 'sq',
  Serbian: 'sr',
  Swati: 'ss',
  Sotho: 'st',
  Sundanese: 'su',
  Swedish: 'sv',
  Swahili: 'sw',
  Tamil: 'ta',
  Telugu: 'te',
  Tajik: 'tg',
  Thai: 'th',
  Tigrinya: 'ti',
  Turkmen: 'tk',
  Tagalog: 'tl',
  Tswana: 'tn',
  'Tonga (Tonga Islands)': 'to',
  Turkish: 'tr',
  Tsonga: 'ts',
  Tatar: 'tt',
  Twi: 'tw',
  Tahitian: 'ty',
  Uyghur: 'ug',
  Ukrainian: 'uk',
  Urdu: 'ur',
  Uzbek: 'uz',
  Venda: 've',
  Vietnamese: 'vi',
  Volapük: 'vo',
  Walloon: 'wa',
  Wolof: 'wo',
  Xhosa: 'xh',
  Yiddish: 'yi',
  Yoruba: 'yo',
  Zhuang: 'za',
  Chinese: 'zh',
  Zulu: 'zu',
};

export { langsByCode, langsByName };
