name: 🖊️ Validate PR Title

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate-pr:
    name: Validate PR Title
    permissions: write-all
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: aslafy-z/conventional-pr-title-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
